DEFAULT_CONFIG = {
    'SECRET_CAPTCHA_KEY': 'CHANGEME - 40 or 50 character long key here',
    'CAPTCHA_LENGTH': 6,
    'CAPTCHA_DIGITS': False,
    # 'EXPIRE_MINUTES': 10,
    'UNIQUE_SALT_LENGTH': 16,
    # 10 minutes, EXPIRE_SECONDS will take prioritity over EXPIRE_MINUTES
    # if both are set.
    'EXPIRE_SECONDS': 60 * 10,
}

# normalize jwt expiration time to seconds
if 'EXPIRE_NORMALIZED' not in DEFAULT_CONFIG:
    if 'EXPIRE_MINUTES' in DEFAULT_CONFIG and 'EXPIRE_SECONDS' not in DEFAULT_CONFIG:
        EXPIRE_NORMALIZED = DEFAULT_CONFIG['EXPIRE_MINUTES'] * 60
    else:
        EXPIRE_NORMALIZED = DEFAULT_CONFIG['EXPIRE_SECONDS']

    DEFAULT_CONFIG['EXPIRE_NORMALIZED'] = EXPIRE_NORMALIZED